export default {
  nav: {
    home: 'Home',
    features: 'Features',
    ai: 'Artificial Intelligence',
    try: 'Try it',
    cta: 'Install Plugin',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    language: 'Language',
  },
  hero: {
    eyebrow: 'A project by',
    title: 'Geographic intelligence in WordPress',
    subtitle:
      'An open WordPress plugin that connects content, maps and territories.',
    workshops: 'Workshops',
    docs: 'Documentation',
    download: 'Download',
    illustrationAlt:
      'Animated illustration of a location search: a pin drops onto map cards while text bars build up and sparkles pop around it',
  },
  showcase: {
    title: 'Smart features',
    lead: "Beyond geolocation and maps, JEO uses automation and artificial intelligence to reduce manual work, make better use of your site's archive and create new ways for readers to discover content. All of it integrated with WordPress, with you in control of what gets added to your content.",
    features: {
      geolocation: {
        title: 'AI-assisted geolocation',
        subtitle: 'Structure locations with less manual work',
        body: 'JEO analyzes new and already published content, identifies the places mentioned and suggests primary and secondary locations. You review the suggestions before adding them to your content.',
        alt: 'WordPress editor with AI-assisted geolocation suggestions',
      },
      minimaps: {
        title: 'Mini-maps per publication',
        subtitle: 'Give geographic context to every piece of content',
        body: 'Create and insert mini-maps in your content in just a few clicks, taking advantage of the locations, layers and other resources available in JEO. Adjust each map to match the content and what you want to highlight.',
        alt: 'Interactive mini-map embedded in a publication',
      },
      recommendations: {
        title: 'Recommendations by topic and territory',
        subtitle: 'Help your visitors discover more of your archive',
        body: 'Relate publications by combining thematic affinity and geographic proximity. This way, each piece of content can open new paths into what already exists on your site.',
        alt: 'Recommendations of related publications by topic and territory',
      },
      stories: {
        title: 'Stories near me',
        subtitle: 'Help your visitors discover what is around them',
        body: 'Allow visitors to find content related to their location. The feature can be embedded in different pages and experiences of the site, creating new ways to explore the archive through territory.',
        alt: 'Page with stories near the visitor location',
      },
      context: {
        title: 'Additional context with AI',
        subtitle: 'Make the most of the knowledge accumulated on your site',
        body: 'Building on your published archive, artificial intelligence suggests short context passages related to the content being edited, helping you recover and reuse relevant information that is already on your site.',
        alt: 'Sidebar with additional context suggestions generated by AI',
      },
    },
  },
  hiw: {
    title: 'Start your own way',
    lead: 'JEO adapts to your project. Start from the content already on your WordPress site or from the features that solve what you need today, and combine new possibilities whenever you want.',
    steps: [
      {
        title: 'Install the Plugin',
        body: 'Add JEO Maps straight from the plugins library of your WordPress site. JEO is modular, and we are available to give you all the support you need.',
      },
      {
        title: 'Geolocate your content',
        body: "Write new posts or edit the ones already in your archive to geolocate them. From there, use JEO for a specific need and incorporate new possibilities as your project evolves. You don't need to start out building maps or adopt every feature at once.",
      },
      {
        title: 'Go further whenever you want',
        body: 'Create maps, generate context for your content and build new forms of discovery. If you already work with geographic data, you can also connect layers from different sources, such as Mapbox, ArcGIS, TileJSON and raster maps. By combining JEO features, you create richer experiences for your readers.',
      },
    ],
  },
  workshops: {
    cardTitle: 'Launch workshops',
    cardLead: 'Try JEO in practice!',
    cardBody:
      'Join our workshop and explore JEO inside WordPress. Test different features, see how they can be combined and discover which possibilities make sense for your project.',
    formNameLabel: 'Name',
    formNamePlaceholder: 'your name',
    formEmailLabel: 'E-mail',
    formEmailPlaceholder: 'your-email@organization.org',
    formSubmit: 'Register for the workshop',
    formSuccess: 'Registrations open soon',
    communityTitle: 'OPEN SOURCE, MORE AUTONOMY',
    communityBody: [
      "JEO is an open source project. You can use, inspect and adapt its code, as well as contribute to the tool's development and propose improvements.",
      "Artificial intelligence is optional: JEO's main features work without it. You choose which features and integrations to activate according to your project's needs.",
      'Some external services — such as certain map or artificial intelligence providers — may require their own access keys and have specific costs, terms and conditions. JEO lets you choose how and when to use them.',
    ],
    communityGithub: 'GitHub repository',
    communityDocs: 'Access the documentation',
  },
  footer: {
    navLabel: 'Footer navigation',
    cta: 'Install for free',
    termsLead: 'Read the',
    termsLink: 'Terms of use and privacy',
    production: 'production',
    development: 'development',
  },
  consent: {
    label: 'Cookies and terms of use notice',
    body: 'We use cookies to improve your experience. By continuing to browse, you agree to our',
    terms: 'terms of use',
    tail: 'and to the use of cookies.',
    accept: 'Accept',
  },
  demo: {
    title: 'SEE JEO IN ACTION',
    address: 'redacao.infoamazonia.org/wp-admin',
    printAlt:
      'WordPress editor (wp-admin) running JEO Maps, shown in a browser window',
    cta: 'Try JEO',
  },
  slider: {
    title: 'content and territories in WordPress',
    lead: 'JEO is a geographic publishing platform integrated with WordPress. It allows newsrooms, organizations and other digital projects to connect their content to places, create interactive maps and turn territory into part of the browsing experience.',
    tabs: {
      geo: 'Geolocation',
      maps: 'Maps & Layers',
      stories: 'Storytelling',
      data: 'Explore data',
    },
    mediaAlt: {
      geo: 'AI-assisted geolocation animation: place suggestions appear in a list while AI sparkles float over the text',
      maps: 'Map layers animation: layer panels slide in until the map is assembled',
      stories: 'Stories on the map animation: waves of story cards float up over a map of Brazil',
      data: 'Data exploration animation: news icons pop in connected by lines, forming a recommendation network',
    },
    cards: {
      geo: {
        title: 'Geolocate your content',
        body: 'Associate publications with one or more places and turn location into structured information in WordPress. This content can then be displayed on maps and used in different ways of navigating the site.',
      },
      maps: {
        title: 'Mini-maps per publication',
        body: 'Create and insert mini-maps into your content in just a few clicks, taking advantage of the locations, layers and other resources available in JEO. Adjust each map according to the content and what you want to highlight.',
      },
      stories: {
        title: 'Stories near me',
        body: 'Let visitors find content related to their location. The feature can be embedded into different pages and experiences of the site, creating new ways to explore the archive from the territory.',
      },
      data: {
        title: 'Recommendations by topic and territory',
        body: 'Connect publications by combining thematic affinity and geographic proximity. This way, each piece of content can open new paths to explore what already exists on your site.',
      },
    },
  },
}
