<?php
/**
 * Conversation management for AI georeferencing sessions.
 *
 * Provides persistent, multi-turn georeferencing via the ai-assistant
 * ConversationStore abstraction. Each session is keyed by a UUID and
 * stored in post_meta so that editors can refine AI suggestions
 * interactively instead of repeating one-shot requests.
 *
 * @package Jeo
 */

namespace Jeo\AI;

use HackLab\AIAssistant\Persistence\ConversationStore;
use NeuronAI\Chat\Messages\AssistantMessage;
use NeuronAI\Chat\Messages\UserMessage;

if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Georeferencing Conversation Manager
 *
 * Wraps ConversationStore with georeferencing-specific helpers:
 * - Load history for a given post + session
 * - Inject history into an Assistant instance
 * - Persist user message + assistant response
 * - List active sessions for a post
 */
class Georeferencing_Conversation {

	/**
	 * WordPress meta key prefix for session IDs.
	 *
	 * @var string
	 */
	const META_PREFIX = '_jeo_geo_conv_';

	/**
	 * Maximum messages to keep per session (prevents meta bloat).
	 *
	 * @var int
	 */
	const MAX_MESSAGES = 20;

	/**
	 * Post ID for this conversation.
	 *
	 * @var int
	 */
	protected int $post_id;

	/**
	 * Conversation session UUID.
	 *
	 * @var string
	 */
	protected string $conversation_id;

	/**
	 * Underlying ConversationStore instance.
	 *
	 * @var ConversationStore
	 */
	protected ConversationStore $store;

	/**
	 * Constructor.
	 *
	 * @param int    $post_id         WordPress post ID.
	 * @param string $conversation_id Session UUID (generated by frontend).
	 */
	public function __construct( int $post_id, string $conversation_id ) {
		$this->post_id         = $post_id;
		$this->conversation_id = $conversation_id;
		$this->store           = new ConversationStore( new WP_Storage( $post_id, 'post' ) );
	}

	/**
	 * Check if a session exists (has any messages).
	 *
	 * @return bool
	 */
	public function exists(): bool {
		$thread = $this->store->loadThread( $this->conversation_id );
		return ! empty( $thread );
	}

	/**
	 * Start a new session with an initial user message.
	 *
	 * @param string $title   Post title.
	 * @param string $content Post content.
	 * @return void
	 */
	public function start( string $title, string $content ): void {
		$this->store->saveThread(
			$this->conversation_id,
			array(
				array(
					'role'    => 'user',
					'content' => "Title: {$title}\n\nContent: {$content}",
				),
			)
		);
		$this->track_session();
	}

	/**
	 * Add a user refinement message to the session.
	 *
	 * @param string $message Refinement text (e.g. "add more locations").
	 * @return void
	 */
	public function add_user_message( string $message ): void {
		$thread   = $this->store->loadThread( $this->conversation_id );
		$thread[] = array(
			'role'    => 'user',
			'content' => $message,
		);
		$thread   = $this->trim_thread( $thread );
		$this->store->saveThread( $this->conversation_id, $thread );
	}

	/**
	 * Add an assistant response to the session.
	 *
	 * @param string $response Assistant response text (JSON or plain).
	 * @return void
	 */
	public function add_assistant_message( string $response ): void {
		$thread   = $this->store->loadThread( $this->conversation_id );
		$thread[] = array(
			'role'    => 'assistant',
			'content' => $response,
		);
		$thread   = $this->trim_thread( $thread );
		$this->store->saveThread( $this->conversation_id, $thread );
	}

	/**
	 * Inject conversation history into an Assistant instance.
	 *
	 * @param \HackLab\AIAssistant\Assistant $assistant Assistant to populate.
	 * @return void
	 */
	public function inject_into( $assistant ): void {
		$thread  = $this->store->loadThread( $this->conversation_id );
		$history = $assistant->getChatHistory();

		foreach ( $thread as $msg ) {
			$text = is_string( $msg['content'] ) ? $msg['content'] : wp_json_encode( $msg['content'] );
			if ( 'assistant' === $msg['role'] ) {
				$history->addMessage( new AssistantMessage( $text ) );
			} else {
				$history->addMessage( new UserMessage( $text ) );
			}
		}
	}

	/**
	 * Get the full conversation thread.
	 *
	 * @return array{array{role:string,content:string}}
	 */
	public function get_thread(): array {
		return $this->store->loadThread( $this->conversation_id );
	}

	/**
	 * Delete the session.
	 *
	 * @return void
	 */
	public function delete(): void {
		$this->store->deleteThread( $this->conversation_id );
		delete_post_meta( $this->post_id, self::META_PREFIX . $this->conversation_id );
	}

	/**
	 * List all active session IDs for a post.
	 *
	 * @param int $post_id Post ID.
	 * @return array<string>
	 */
	public static function list_sessions( int $post_id ): array {
		$meta    = get_post_meta( $post_id );
		$session = array();
		foreach ( array_keys( $meta ) as $key ) {
			if ( str_starts_with( $key, self::META_PREFIX ) ) {
				$session[] = substr( $key, strlen( self::META_PREFIX ) );
			}
		}
		return $session;
	}

	/**
	 * Keep the session ID registry in post_meta for easy listing.
	 *
	 * @return void
	 */
	protected function track_session(): void {
		update_post_meta( $this->post_id, self::META_PREFIX . $this->conversation_id, time() );
	}

	/**
	 * Trim thread to MAX_MESSAGES (keeps most recent).
	 *
	 * @param array{array{role:string,content:string}} $thread Raw thread.
	 * @return array{array{role:string,content:string}}
	 */
	protected function trim_thread( array $thread ): array {
		if ( count( $thread ) <= self::MAX_MESSAGES ) {
			return $thread;
		}
		return array_slice( $thread, -self::MAX_MESSAGES );
	}
}
